apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: biljardturnering
  namespace: bussfaktor
  labels:
    team: bussfaktor
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 32Mi
  strategy:
    type: Recreate    
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        groups:
          - id: "55a93a3d-9ecb-4e76-af06-85ef2e32ff98" 
        extra:
          - NAVident
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /api/internal/*
  env:
    - name: ADMIN_GROUP_ID
      value: "55a93a3d-9ecb-4e76-af06-85ef2e32ff98" 
  filesFrom:
    - persistentVolumeClaim: biljard-data
      mountPath: /app/data
  ingresses:
    - https://biljard.intern.dev.nav.no
