apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: biljard
  namespace: bussfaktor
  labels:
    team: bussfaktor
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  strategy:
    type: Recreate
  terminationGracePeriodSeconds: 30    
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        groups:
          - id: "95c8e577-168f-4c03-b14e-658947a94f3a" 
        extra:
          - NAVident
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /api/internal/*
  env:
    - name: ADMIN_GROUP_ID
      value: "95c8e577-168f-4c03-b14e-658947a94f3a" 
  filesFrom:
    - persistentVolumeClaim: biljard-data
      mountPath: /app/data
  ingresses:
    - https://biljard.nav.no
